image:
  registry: "093747270488.dkr.ecr.eu-west-2.amazonaws.com"
  tag: "latest"

services:
  cartservice:
    port: 7070
    replicas: 3
    resources:
      requests: { cpu: "100m", memory: "128Mi" }
      limits:   { cpu: "200m", memory: "256Mi" }

  checkoutservice:
    port: 5050
    replicas: 2
    resources:
      requests: { cpu: "100m", memory: "64Mi" }
      limits:   { cpu: "200m", memory: "128Mi" }
    env:
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:7000"
      - name: CART_SERVICE_ADDR
        value: "cartservice:7070"
      - name: PAYMENT_SERVICE_ADDR
        value: "paymentservice:50051"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:50051"
      - name: EMAIL_SERVICE_ADDR
        value: "emailservice:8080"

  currencyservice:
    port: 7000
    replicas: 2
    resources:
      requests: { cpu: "100m", memory: "64Mi" }
      limits:   { cpu: "200m", memory: "128Mi" }
    env:
      - name: PORT
        value: "7000"
      - name: DISABLE_PROFILER
        value: "1"

  emailservice:
    port: 8080
    replicas: 2
    resources:
      requests: { cpu: "100m", memory: "64Mi" }
      limits:   { cpu: "200m", memory: "128Mi" }

  frontend:
    port: 8080
    replicas: 2
    type: LoadBalancer
    resources:
      requests: { cpu: "100m", memory: "128Mi" }
      limits:   { cpu: "200m", memory: "256Mi" }
    env:
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:7000"
      - name: CART_SERVICE_ADDR
        value: "cartservice:7070"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "recommendationservice:8080"
      - name: CHECKOUT_SERVICE_ADDR
        value: "checkoutservice:5050"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:50051"
      - name: AD_SERVICE_ADDR
        value: "adservice:9555"
      - name: SHOPPING_ASSISTANT_SERVICE_ADDR
        value: "shoppingassistantservice:8080"

  paymentservice:
    port: 50051
    replicas: 2
    resources:
      requests: { cpu: "100m", memory: "64Mi" }
      limits:   { cpu: "200m", memory: "128Mi" }
    env:
      - name: PORT
        value: "50051"
      - name: DISABLE_PROFILER
        value: "1"

  productcatalogservice:
    port: 3550
    replicas: 2
    resources:
      requests: { cpu: "100m", memory: "128Mi" }
      limits:   { cpu: "200m", memory: "256Mi" }

  recommendationservice:
    port: 8080
    replicas: 2
    resources:
      requests: { cpu: "100m", memory: "220Mi" }
      limits:   { cpu: "200m", memory: "450Mi" }
    env:
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"

  shippingservice:
    port: 50051
    replicas: 2
    resources:
      requests: { cpu: "100m", memory: "64Mi" }
      limits:   { cpu: "200m", memory: "128Mi" }

  adservice:
    port: 9555
    replicas: 2
    resources:
      requests: { cpu: "100m", memory: "180Mi" }
      limits:   { cpu: "300m", memory: "300Mi" }

  loadgenerator:
    replicas: 1
    noService: true
    resources:
      requests: { cpu: "100m", memory: "128Mi" }
      limits:   { cpu: "200m", memory: "256Mi" }
    env:
      - name: FRONTEND_ADDR
        value: "frontend:8080"
