apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency
  name: currencyservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
        - image: 093747270488.dkr.ecr.eu-west-2.amazonaws.com/currencyservice
          name: currencyservice
          ports:
            - name: currency-port
              containerPort: 7000
          env:
            - name: PORT
              value: "7000"
            - name: DISABLE_PROFILER
              value: "1"
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
