apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: email
  name: emailservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - image: 093747270488.dkr.ecr.eu-west-2.amazonaws.com/emailservice
          name: emailservice
          ports:
            - name: email-port
              containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
